/*
 * Script to initialize the database.
 */


CREATE TYPE actors_available AS ENUM ('member', 'organization');

CREATE TABLE actors (
	id text PRIMARY KEY,
	actortype actors_available
);

CREATE TABLE messages ( -- Column names are used as JSON key name
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	content text NOT NULL,
	time timestamptz NOT NULL,
	history bigint
);

CREATE TABLE messages_changes (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	version bigint REFERENCES messages,
	PRIMARY KEY (id, version)
);

CREATE FUNCTION check_changelog() RETURNS trigger AS $check_changelog$
	DECLARE
		actortype actors_available;
  BEGIN
    IF NEW.changelog <> NULL AND NOT NEW.changelog IN (SELECT id from messages_changes) THEN
      RAISE EXCEPTION 'invaild update';
    END IF;

    RETURN NEW;
  END;
$check_changelog$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER check_changelog AFTER INSERT OR UPDATE ON messages
	FROM messages_changes
	FOR EACH ROW
	EXECUTE FUNCTION check_changelog();

CREATE TABLE messages_sent (
	actor text REFERENCES actors,
	message bigint REFERENCES messages,
	PRIMARY KEY (actor, message)
);

CREATE TABLE messages_recieved (
	actor text REFERENCES actors,
	message bigint REFERENCES messages,
	PRIMARY KEY (actor, message)
);

CREATE TABLE belongings (
	-- "user" and "group" are both reserved
	member text REFERENCES actors,
	organization text REFERENCES actors,
	-- privilege
	PRIMARY KEY (member, organization)
);

CREATE FUNCTION check_actor_type() RETURNS trigger AS $check_actor_type$
	DECLARE
		actortype actors_available;
  BEGIN

    SELECT type INTO actortype FROM actors WHERE id = NEW.member;
    IF actortype <> 'member' THEN
      RAISE EXCEPTION 'a group id is passed in place of user id';
    END IF;

		SELECT type INTO actortype FROM actors WHERE id = NEW.organization;
    IF actortype <> 'organization' THEN
      RAISE EXCEPTION 'a user id is passed in place of group id';
		END IF;

    RETURN NEW;
  END;
$check_actor_type$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER check_type AFTER INSERT OR UPDATE ON belongings
	FROM actors
	FOR EACH ROW
	EXECUTE FUNCTION check_actor_type();